# Azure DevOps pipeline for Azure deployment

variables:
- group: globomantics

trigger:
  branches:
    include:
    - main

stages:
- stage: development
  displayName: development
  jobs:
  - deployment: deploy
    environment: development
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
      
          # Init
          - task: TerraformTask@5
            displayName: Initialize Terraform
            env:
              ARM_SAS_TOKEN: $(sas_token)
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              backendServiceArm: 'Networking_Sub'
              backendAzureRmStorageAccountName: '$(storage_account_name)'
              backendAzureRmContainerName: 'terraform-state'
              backendAzureRmKey: 'terraform.tfstate'
      
          # Check for workspace
          - task: Bash@3
            displayName: Check for Workspace
            inputs:
              targetType: 'filePath'
              filePath: '$(System.DefaultWorkingDirectory)/networking/workspacetest.sh'
              arguments: '$(Environment.Name)'
      
          - task: TerraformTask@5
            displayName: Plan Terraform Deployment
            env:
              TF_WORKSPACE: '$(Environment.Name)'
              TF_VAR_sec_client_secret: $(sec_client_secret)
              ARM_SAS_TOKEN: $(sas_token)
            inputs:
              command: 'plan'
              commandOptions: '-out main.tfplan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              environmentServiceNameAzureRM: 'Networking_Sub'
      
          - task: TerraformTask@5
            displayName: Apply Terraform Deployment
            env:
              TF_WORKSPACE: '$(Environment.Name)'
              TF_VAR_sec_client_secret: $(sec_client_secret)
              ARM_SAS_TOKEN: $(sas_token)
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              commandOptions: 'main.tfplan'
              environmentServiceNameAzureRM: 'Networking_Sub'